version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multiagent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "neo4j/changeme"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"  
      - "7687:7687"   
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

  # Optional API (FastAPI)
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    container_name: multiagent_api
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - neo4j
    environment:
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/multiagent
      - REDIS_URL=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changeme

  worker:
    build:
      context: .
      dockerfile: infra/Dockerfile.worker
    container_name: multiagent_worker
    restart: unless-stopped
    command: poetry run python -m app.cli run --amount 10000
    depends_on:
      - postgres
      - redis
      - neo4j
    environment:
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/multiagent
      - REDIS_URL=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changeme
      - KITE_API_KEY=your_key
      - KITE_API_SECRET=your_secret
      - PAPER_MODE=true
      - APP_ENV=development

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
